# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 397e70f71ec2509ef946382cefa098ebc174063857db7f99796e8ece79f0f1f8a7dee38752cd7d9c15e69a3181352e82a657b6ec6a66cae2b9840171bbc03722

test:
  secret_key_base: 98184043c67422bf5681689365b799a4b4f9e58fd816542e3646aeb81781ce16dcf011c3557d6cb97c13d79eefeec3550f4954b34fe207a6ce520a14192721a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
